class Data(object):
    
    showTables = {
        'basic_estimate':
        [
            'id',
            'chapter_id',
            'number_in_order',
            'estimate_id',
            'estimate_number',
            'justification_id',
            'Year',
            'notes',
            'grey',
            'name_id',
            'contractor_id',
            'dimension',
            'value',
            'cost',
            'tbas',
            'wpi',
            'executive_documentation'
        ],
        'chapter':
        [
            'id',
            'name',
            'number'
        ],
        'contractor':
        [
            'id',
            'name',
            'full_name'
        ],
        'dimension':
        [
            'id',
            'name',
            'multiplicity'
        ],
        'estimate_number':
        [
            'id',
            'estimate'
        ],
        'executive_documentation':
        [
            'id',
            'id_contractor',
            'val_number',
            'name',
            'passed',
            'dttc',
            'notes_id',
            'note'
        ],
        'justification':
        [
            'id',
            'position'
        ],
        'name_of_works_and_materials':
        [
            'id',
            'name'
        ],
        'notes':
        [
            'id',
            'note'
        ],
        'people':
        [
            'id',
            'f_name',
            'l_name',
            'm_name',
            'initials',
            'position',
            'email',
            'phone_number',
            'company_id'
        ]
    }
    listTmp = ['chapter_id','notes','executive_documentation','Year','tbas', 'wpi']
    dataKey = {
        'contractor_id':['contractor',6],
        'dimension':['dimension',7],
        'estimate_id':['estimate_number',2],
        'justification_id':['justification',4],
        'name_id':['name_of_works_and_materials',5],
        'estimate_number':['',3],
        'value':['',8],
        'cost':['',11],
        'grey':['grey',1],
        'number_in_order':['number_in_order',1]
    }